apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jsonrpc-wrapper.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jsonrpc-wrapper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jsonrpc-wrapper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jsonrpc-wrapper.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "jsonrpc-wrapper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONNECT_STRING_REDIS
              valueFrom:
                secretKeyRef:
                  name: rpi-config
                  key: CONNECT_STRING_REDIS
            - name: CONNECT_STRING_DOCUMENTDB
              valueFrom:
                secretKeyRef:
                  name: rpi-config
                  key: CONNECT_STRING_DOCUMENTDB
            - name: DOCUMENTDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: rpi-config
                  key: DOCUMENTDB_DATABASE
            - name: ADMIN_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: rpi-config
                  key: ADMIN_PUBLIC_KEY
            - name: SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: rpi-config
                  key: SMTP_SERVER
            - name: SMTP_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: rpi-config
                  key: SMTP_ACCOUNT
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rpi-config
                  key: SMTP_PASSWORD
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: rpi-config
                  key: SMTP_PORT
                
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /v1/healthz
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
